---
- name: restart mesos-master
  service: name=mesos-master state=restarted

- name: stop mesos-master
  service: name=mesos-master state=stopped
 
- name: start mesos-slave
  service: name=mesos-slave state=started
  become: yes
 
- name: stop mesos-slave
  service: name=mesos-slave state=stopped
  become: yes

- name: restart zookeeper
  service: name=zookeeper state=restarted
 
- name: stop zookeeper
  service: name=zookeeper state=stopped