---
  - name: Update apt
    become: yes
    apt:  update_cache=yes
    
  - name: Install system packages
    become: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - curl
      - wget
      - zip
      - unzip

  - name: Install extra packages
    become: yes
    apt:  pkg={{ item }} state=latest
    with_items: "{{ sys_packages }}"
