mesos_version: mesos
marathon_version: marathon
mesos_cluster_name: "MesosCluster01"
mesos_quorum_count: "1"
zookeeper_client_port: "2181"
zookeeper_leader_port: "2888"
zookeeper_election_port: "3888"
zookeeper_url: "zk://{{ groups.zookeepers | join(':' + zookeeper_client_port + ',') }}:{{ zookeeper_client_port }}"
sys_packages:
  