---
- name: Install marathon package
  apt: pkg={{ marathon_version }} state=present update_cache=yes
  become: yes
  register: marathon_install
 
- name: Create Marathon Upstart job for packaged version
  template: src=marathon.conf.j2 dest=/etc/init/marathon.conf
  become: yes
  when: marathon_install | changed
  notify:
    - restart marathon